
project_id = "vjlfwmwhvxlicykqetnk"

[functions.recommend]
verify_jwt = false

[functions.conversational-recommend]
verify_jwt = false

[functions.me-webhook]
verify_jwt = false

[functions.redeem-points]
verify_jwt = false

[functions.me-delete]
verify_jwt = false

[functions.create-stripe-checkout]
verify_jwt = true

[functions.tasks/db-backup]
verify_jwt = false

[functions.cart-recovery]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.email-triggers]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.search-analytics]
verify_jwt = false

[functions.check-secrets]
verify_jwt = true

[functions.public-analytics-config]
verify_jwt = false

[functions.password-pwned-check]
verify_jwt = false

# New: expose the webhook publicly (Stripe won't send JWT)
[functions.stripe-webhook]
verify_jwt = false

# Allow webhook to call confirm-order without JWT
[functions.confirm-order]
verify_jwt = false
