project_id = "vjlfwmwhvxlicykqetnk"

[functions.recommend]
verify_jwt = false

[functions.conversational-recommend]
verify_jwt = false

[functions.me-webhook]
verify_jwt = false

[functions.redeem-points]
verify_jwt = false

[functions.me-delete]
verify_jwt = false

[functions.me-buy-label]
verify_jwt = true

[functions.create-stripe-checkout]
verify_jwt = true

[functions.tasks/db-backup]
verify_jwt = false

[functions.cart-recovery]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.email-triggers]
verify_jwt = false

[functions.voice-to-text]
verify_jwt = false

[functions.search-analytics]
verify_jwt = false

[functions.check-secrets]
verify_jwt = true

[functions.public-analytics-config]
verify_jwt = false

[functions.password-pwned-check]
verify_jwt = false

# New: expose the webhook publicly (Stripe won't send JWT)
[functions.stripe-webhook]
verify_jwt = false

# Allow webhook to call confirm-order without JWT
[functions.confirm-order]
verify_jwt = false

# New automation functions
[functions.generate-nfe]
verify_jwt = true

[functions.schedule-collection]
verify_jwt = true

[functions.download-label]
verify_jwt = true

[functions.process-payment-automation]
verify_jwt = true

[functions.generate-sitemap]
verify_jwt = false

[functions.cancel-nfe]
verify_jwt = true

[functions.subscription-checkout]
verify_jwt = true

[functions.subscription-webhook]
verify_jwt = false

[functions.process-monthly-subscriptions]
verify_jwt = false

[functions.verify-2fa]
verify_jwt = true
